<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="atlantik_solar" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Global properties -->
  <xacro:property name="namespace" value="$(arg mav_name)" />
  <xacro:property name="propeller_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="false" />
  <xacro:property name="mesh_file" value="" />

  <!-- Component masses -->
  <xacro:property name="mass_fuselage" value="3.0" /> <!-- [kg] -->
  <xacro:property name="mass_wheel" value="0.05" /> <!-- [kg] -->
  <xacro:property name="mass_front_wing" value="1.0" /> <!-- [kg] -->
  <xacro:property name="mass_tail" value="0.5" /> <!-- [kg] -->
  <xacro:property name="mass_rear_wing" value="0.2" /> <!-- [kg] -->
  <xacro:property name="mass_propeller" value="0.01" /> <!-- [kg] -->
  <xacro:property name="mass_rudder" value="0.2" /> <!-- [kg] -->

  <!-- Fuselage properties -->
  <xacro:property name="body_length" value="3.0" /> <!-- [m] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_color" value="Red" />

  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.05" /> <!-- [m] -->
  <xacro:property name="wheel_width" value="0.01" /> <!-- [m] -->

  <!-- Propeller properties -->
  <xacro:property name="propeller_offset" value="0.025" /> <!-- [m] -->
  <xacro:property name="radius_propeller" value="0.15" /> <!-- [m] -->
  <xacro:property name="motor_constant" value="6.14858e-04" /> <!-- [kg m/s^2] -->
  <xacro:property name="moment_constant" value="0.016" /> <!-- [m] -->
  <xacro:property name="time_constant_up" value="0.0125" /> <!-- [s] -->
  <xacro:property name="time_constant_down" value="0.025" /> <!-- [s] -->
  <xacro:property name="max_propeller_velocity" value="838" /> <!-- [rad/s] -->
  <xacro:property name="rotor_drag_coefficient" value="8.06428e-05" />
  <xacro:property name="rolling_moment_coefficient" value="0.000001" />

  <!-- Wing properties -->
  <xacro:property name="wingspan" value="4.0" /> <!-- [m] -->
  <xacro:property name="root_chord" value="0.3" /> <!-- [m] -->
  <xacro:property name="front_wing_height" value="0.02" /> <!-- [m] -->
  <xacro:property name="front_wing_dihedral_angle" value="5" /> <!-- [deg] -->
  <xacro:property name="rear_wingspan" value="1.0" /> <!-- [m] -->
  <xacro:property name="rear_wing_height" value="0.02" /> <!-- [m] -->
  <xacro:property name="alpha_0" value="0.02" /> <!-- [rad] -->
  <xacro:property name="alpha_stall" value="0.2" /> <!-- [rad] -->
  <xacro:property name="c_L_alpha" value="4.0" />
  <xacro:property name="air_density" value="1.225" /> <!-- [kg/m^3] -->

  <!-- Tail properties -->
  <xacro:property name="tail_length" value="0.4" /> <!-- [m] -->
  <xacro:property name="tail_width" value="0.05" /> <!-- [m] -->
  <xacro:property name="tail_height" value="0.3" /> <!-- [m] -->

  <!-- Rudder properties -->
  <xacro:property name="rudder_length" value="0.1" /> <!-- [m] -->
  <xacro:property name="rudder_width" value="${tail_width}" /> <!-- [m] -->
  <xacro:property name="rudder_height" value="${tail_height}" /> <!-- [m] -->
  <xacro:property name="rudder_velocity_gain" value="1.0" />
  <xacro:property name="rudder_min_angle" value="-0.55" /> <!-- [rad] -->
  <xacro:property name="rudder_max_angle" value="0.55" /> <!-- [rad] -->

  <!-- Constants -->
  <xacro:property name="PI" value="3.1415926535897931" />

  <!-- Front wing length -->
  <xacro:property name="front_wing_length" value="${0.5 * (wingspan - body_width) / 
    (1.0 - 0.5 * (front_wing_dihedral_angle * front_wing_dihedral_angle * PI * PI / (180.0 * 180.0)))}" />

  <!-- Rear wing length -->
  <xacro:property name="rear_wing_length" value="${0.5 * (rear_wingspan - tail_width)}" />

  <!-- Inertia of the fuselage -->
  <xacro:property name="body_inertia">
    <xacro:box_inertia x="${body_length}" y="${body_width}" z="${body_height}" mass="${mass_fuselage}" />
  </xacro:property>

  <!-- Inertia of a single wheel, assuming it is a cylinder -->
  <xacro:property name="wheel_inertia">
    <xacro:cylinder_inertia r="${wheel_radius}" h="${wheel_width}" mass="${mass_wheel}" />
  </xacro:property>

  <!-- Inertia of a single front wing, assuming it is a cuboid -->
  <xacro:property name="front_wing_inertia">
    <xacro:box_inertia x="${front_wing_length}" y="${tail_length}" z="${rear_wing_height}" mass="${mass_front_wing}" />
  </xacro:property>

  <!-- Inertia of the tail, assuming it is a cuboid -->
  <xacro:property name="tail_inertia">
    <xacro:box_inertia x="${tail_length}" y="${tail_width}" z="${tail_height}" mass="${mass_tail}" />
  </xacro:property>

  <!-- Inertia of a single rear wing, assuming it is a cuboid -->
  <xacro:property name="rear_wing_inertia">
    <xacro:box_inertia x="${rear_wing_length}" y="${tail_width}" z="${tail_height}" mass="${mass_rear_wing}" />
  </xacro:property>

  <!-- Inertia of the propeller, assuming it is a cuboid. Height=3mm, width=40mm -->
  <xacro:property name="propeller_inertia">
    <xacro:box_inertia x="${radius_propeller}" y="0.04" z="0.003" mass="${mass_propeller * propeller_velocity_slowdown_sim}" />
  </xacro:property>

  <!-- Inertia of the rudder, assuming it is a cuboid -->
  <xacro:property name="rudder_inertia">
    <xacro:box_inertia x="${rudder_length}" y="${rudder_width}" z="${rudder_height}" mass="${mass_rudder}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/fixed_wing_base.xacro" />

  <!-- Instantiate fixed_wing_base_macro once -->
  <xacro:fixed_wing_base_macro
    robot_namespace="${namespace}"
    mass="${mass_fuselage}"
    body_length="${body_length}"
    body_width="${body_width}"
    body_height="${body_height}"
    color="${body_color}"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}">
    <xacro:insert_block name="body_inertia" />
  </xacro:fixed_wing_base_macro>

  <!-- Instantiate wheels -->
  <xacro:wheel
    robot_namespace="${namespace}"
    suffix="front_left"
    parent="${namespace}/base_link"
    mass_wheel="${mass_wheel}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    wheel_radius="${wheel_radius}"
    wheel_width="${wheel_width}">
    <origin xyz="0.75 0.1 0.0" rpy="${0.5 * PI} 0.0 0.0" />
    <xacro:insert_block name="wheel_inertia" />
  </xacro:wheel>

  <xacro:wheel
    robot_namespace="${namespace}"
    suffix="front_right"
    parent="${namespace}/base_link"
    mass_wheel="${mass_wheel}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    wheel_radius="${wheel_radius}"
    wheel_width="${wheel_width}">
    <origin xyz="0.75 -0.1 0.0" rpy="${0.5 * PI} 0.0 0.0" />
    <xacro:insert_block name="wheel_inertia" />
  </xacro:wheel>

  <xacro:wheel
    robot_namespace="${namespace}"
    suffix="back"
    parent="${namespace}/base_link"
    mass_wheel="${mass_wheel}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    wheel_radius="${wheel_radius}"
    wheel_width="${wheel_width}">
    <origin xyz="-1.0 0.0 0.0" rpy="${0.5 * PI} 0.0 0.0" />
    <xacro:insert_block name="wheel_inertia" />
  </xacro:wheel>

  <!-- Instantiate wings -->
  <xacro:wing
    robot_namespace="${namespace}"
    suffix="left"
    parent="${namespace}/base_link"
    mass_wing="${mass_front_wing}"
    wing_length="${root_chord}"
    wing_width="${front_wing_length}"
    wing_height="${front_wing_height}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}"
    air_density="${air_density}">
    <origin xyz="0.5 ${0.25 * wingspan} 0.1" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="front_wing_inertia" />
  </xacro:wing>-->

  <xacro:wing
    robot_namespace="${namespace}"
    suffix="right"
    parent="${namespace}/base_link"
    mass_wing="${mass_front_wing}"
    wing_length="${root_chord}"
    wing_width="${front_wing_length}"
    wing_height="${front_wing_height}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}"
    air_density="${air_density}">
    <origin xyz="0.5 -${0.25 * wingspan} 0.1" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="front_wing_inertia" />
  </xacro:wing>

  <!-- Instantiate the tail -->
  <xacro:tail
    robot_namespace="${namespace}"
    parent="${namespace}/base_link"
    mass_tail="${mass_tail}"
    tail_length="${tail_length}"
    tail_width="${tail_width}"
    tail_height="${tail_height}"
    color="${body_color}"
    use_mesh="false"
    mesh="">
    <origin xyz="${-0.5*body_length + 0.5*tail_length} 0.0 ${0.5*body_height + 0.5*tail_height + 0.1}" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="tail_inertia" />
  </xacro:tail>

  <!-- Instantiate the rear wings-->
  <xacro:rear_wing
    robot_namespace="${namespace}"
    suffix="left"
    parent="${namespace}/tail"
    mass_rear_wing="${mass_rear_wing}"
    rear_wing_length="${tail_length}"
    rear_wing_width="${rear_wing_length}"
    rear_wing_height="${rear_wing_height}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}">
    <origin xyz="0.0 ${0.25 * (rear_wingspan + tail_width)} ${0.5 * (tail_height - rear_wing_height)}" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="rear_wing_inertia" />
  </xacro:rear_wing>

  <xacro:rear_wing
    robot_namespace="${namespace}"
    suffix="right"
    parent="${namespace}/tail"
    mass_rear_wing="${mass_rear_wing}"
    rear_wing_length="${tail_length}"
    rear_wing_width="${rear_wing_length}"
    rear_wing_height="${rear_wing_height}"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}">
    <origin xyz="0.0 ${-0.25 * (rear_wingspan + tail_width)} ${0.5 * (tail_height - rear_wing_height)}" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="rear_wing_inertia" />
  </xacro:rear_wing>

  <!-- Instantiate the propeller -->
  <xacro:propeller
    robot_namespace="${namespace}"
    direction="cw"
    motor_constant="${motor_constant}"
    moment_constant="${moment_constant}"
    parent="${namespace}/base_link"
    mass_propeller="${mass_propeller}"
    radius_propeller="${radius_propeller}"
    time_constant_up="${time_constant_up}"
    time_constant_down="${time_constant_down}"
    max_propeller_velocity="${max_propeller_velocity}"
    motor_number="0"
    rotor_drag_coefficient="${rotor_drag_coefficient}"
    rolling_moment_coefficient="${rolling_moment_coefficient}"
    color="Blue"
    use_own_mesh="false"
    mesh="">
    <origin xyz="${0.5 * body_length + propeller_offset} 0.0 0.1" rpy="0.0 ${0.5 * PI} 0.0" />
    <xacro:insert_block name="propeller_inertia" />
  </xacro:propeller>

  <!-- Instantiate the control surfaces -->
  <xacro:control_surface
    robot_namespace="${namespace}"
    surface_name="rudder"
    parent="${namespace}/tail"
    mass_surface="${mass_rudder}"
    velocity_gain="${rudder_velocity_gain}"
    min_angle="${rudder_min_angle}"
    max_angle="${rudder_max_angle}"
    channel="0"
    color="${body_color}"
    use_mesh="false"
    mesh=""
    surface_length="${rudder_length}"
    surface_width="${rudder_width}"
    surface_height="${rudder_height}">
    <axis xyz="0 0 1" />
    <origin xyz="${-0.5 * tail_length} 0.0 0.0" rpy="0.0 0.0 0.0" /> <!-- Joint origin -->
    <origin xyz="${-0.5 * rudder_length} 0.0 0.0" rpy="0.0 0.0 0.0" /> <!-- Link origin -->
    <xacro:insert_block name="rudder_inertia" />
  </xacro:control_surface>
</robot>
