<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="atlantik_solar" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <xacro:property name="namespace" value="$(arg mav_name)" />
  <xacro:property name="rotor_velocity_slowdown_sim" value="10" />
  <xacro:property name="use_mesh_file" value="false" />
  <xacro:property name="mesh_file" value="" />
  <xacro:property name="mass_fuselage" value="0.2" /> <!-- [kg] -->
  <xacro:property name="mass_front_wing" value="0.1" /> <!-- [kg] -->
  <xacro:property name="mass_tail" value="0.1" /> <!-- [kg] -->
  <xacro:property name="mass_rear_wing" value="0.1" /> <!-- [kg] -->
  <xacro:property name="body_length" value="3.0" /> <!-- [m] -->
  <xacro:property name="body_width" value="0.1" /> <!-- [m] -->
  <xacro:property name="body_height" value="0.1" /> <!-- [m] -->
  <xacro:property name="wingspan" value="6.0" /> <!-- [m] -->
  <xacro:property name="root_chord" value="0.3" /> <!-- [m] -->
  <xacro:property name="front_wing_height" value="0.02" /> <!-- [m] -->
  <xacro:property name="front_wing_dihedral_angle" value="5" /> <!-- [deg] -->
  <xacro:property name="tail_length" value="0.4" /> <!-- [m] -->
  <xacro:property name="tail_width" value="0.05" /> <!-- [m] -->
  <xacro:property name="tail_height" value="0.3" /> <!-- [m] -->
  <xacro:property name="rear_wingspan" value="1.0" /> <!-- [m] -->
  <xacro:property name="rear_wing_height" value="0.02" /> <!-- [m] -->
  <xacro:property name="max_thrust" value="100.0" /> <!-- [N] -->
  <xacro:property name="alpha_0" value="2.0" /> <!-- [deg] -->
  <xacro:property name="alpha_stall" value="15.0" /> <!-- [deg] -->
  <xacro:property name="c_L_alpha" value="${2.0 * PI}" />
  <xacro:property name="air_density" value="1.225" /> <!-- [kg/m^3] -->
  <xacro:property name="PI" value="3.1415926535897931" />

  <!-- Front wing length -->
  <xacro:property name="front_wing_length" value="${0.5 * (wingspan - body_width) / 
    (1.0 - 0.5 * (front_wing_dihedral_angle * front_wing_dihedral_angle * PI * PI / (180.0 * 180.0)))}" />

  <!-- Rear wing length -->
  <xacro:property name="rear_wing_length" value="${0.5 * (rear_wingspan - tail_width)}" />

  <!-- Inertia of the fuselage -->
  <xacro:property name="body_inertia">
    <xacro:box_inertia x="${body_length}" y="${body_width}" z="${body_height}" mass="${mass_fuselage}" />
  </xacro:property>

  <!-- Inertia of a single front wing, assuming it is a cuboid -->
  <xacro:property name="front_wing_inertia">
    <xacro:box_inertia x="${front_wing_length}" y="${tail_length}" z="${rear_wing_height}" mass="${mass_front_wing}" />
  </xacro:property>

  <!-- Inertia of the tail, assuming it is a cuboid -->
  <xacro:property name="tail_inertia">
    <xacro:box_inertia x="${tail_length}" y="${tail_width}" z="${tail_height}" mass="${mass_tail}" />
  </xacro:property>

  <!-- Inertia of a single rear wing, assuming it is a cuboid -->
  <xacro:property name="rear_wing_inertia">
    <xacro:box_inertia x="${rear_wing_length}" y="${tail_width}" z="${tail_height}" mass="${mass_rear_wing}" />
  </xacro:property>

  <!-- Included URDF Files -->
  <xacro:include filename="$(find rotors_description)/urdf/fixed_wing_base.xacro" />

  <!-- Instantiate fixed_wing_base_macro once -->
  <xacro:fixed_wing_base_macro
    robot_namespace="${namespace}"
    mass="${mass_fuselage}"
    body_length="${body_length}"
    body_width="${body_width}"
    body_height="${body_height}"
    actuator_topic="actuators"
    max_thrust="200.0"
    use_mesh_file="${use_mesh_file}"
    mesh_file="${mesh_file}">
    <xacro:insert_block name="body_inertia" />
  </xacro:fixed_wing_base_macro>

  <!-- Instantiate wings -->
  <xacro:wing
    robot_namespace="${namespace}"
    suffix="left"
    parent="${namespace}/base_link"
    mass_wing="${mass_front_wing}"
    wing_length="${front_wing_length}"
    wing_width="${root_chord}"
    wing_height="${front_wing_height}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}"
    air_density="${air_density}"
    link_x="${0.5*front_wing_length}"
    link_y="0.0"
    link_z="0.0">
    <origin xyz="0.5 ${0.5*body_width} 0.0" rpy="0.0 ${-front_wing_dihedral_angle*PI/180.0} ${PI*0.5}" />
    <xacro:insert_block name="front_wing_inertia" />
  </xacro:wing>-->

  <xacro:wing
    robot_namespace="${namespace}"
    suffix="right"
    parent="${namespace}/base_link"
    mass_wing="${mass_front_wing}"
    wing_length="${front_wing_length}"
    wing_width="${root_chord}"
    wing_height="${front_wing_height}"
    use_mesh="false"
    mesh=""
    alpha_0="${alpha_0}"
    alpha_stall="${alpha_stall}"
    c_L_alpha="${c_L_alpha}"
    air_density="${air_density}"
    link_x="${0.5*front_wing_length}"
    link_y="0.0"
    link_z="0.0">
    <origin xyz="0.5 ${-0.5*body_width} 0.0" rpy="0.0 ${-front_wing_dihedral_angle*PI/180.0} ${-PI*0.5}" />
    <xacro:insert_block name="front_wing_inertia" />
  </xacro:wing>

  <!-- Instantiate the tail -->
  <xacro:tail
    robot_namespace="${namespace}"
    parent="${namespace}/base_link"
    mass_tail="${mass_tail}"
    tail_length="${tail_length}"
    tail_width="${tail_width}"
    tail_height="${tail_height}"
    use_mesh="false"
    mesh="">
    <origin xyz="${-0.5*body_length + 0.5*tail_length} 0.0 ${0.5*body_height + 0.5*tail_height}" rpy="0.0 0.0 0.0" />
    <xacro:insert_block name="tail_inertia" />
  </xacro:tail>

  <!-- Instantiate the rear wings-->
  <xacro:rear_wing
    robot_namespace="${namespace}"
    suffix="left"
    parent="${namespace}/tail"
    mass_rear_wing="${mass_rear_wing}"
    rear_wing_length="${rear_wing_length}"
    rear_wing_width="${tail_length}"
    rear_wing_height="${rear_wing_height}"
    use_mesh="false"
    mesh="">
    <origin xyz="0.0 ${0.25 * (rear_wingspan + tail_width)} ${0.5 * (tail_height - rear_wing_height)}" rpy="0.0 0.0 ${PI*0.5}" />
    <xacro:insert_block name="rear_wing_inertia" />
  </xacro:rear_wing>

  <xacro:rear_wing
    robot_namespace="${namespace}"
    suffix="right"
    parent="${namespace}/tail"
    mass_rear_wing="${mass_rear_wing}"
    rear_wing_length="${rear_wing_length}"
    rear_wing_width="${tail_length}"
    rear_wing_height="${rear_wing_height}"
    use_mesh="false"
    mesh="">
    <origin xyz="0.0 ${-0.25 * (rear_wingspan + tail_width)} ${0.5 * (tail_height - rear_wing_height)}" rpy="0.0 0.0 ${-PI*0.5}" />
    <xacro:insert_block name="rear_wing_inertia" />
  </xacro:rear_wing>
</robot>
